name: 🌱

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: "4.3.1"
      - name: Install R::devtools dependencies on Ubuntu
        run: |
          sudo apt install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - name: Install dependencies on R
        run: |
          install.packages(c("devtools", "testthat", "doParallel", "foreach", "txtplot", "sommer"))
        shell: Rscript {0}
      - name: Install simquantgen
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          devtools::install_github("jeffersonfparil/simquantgen")
        shell: Rscript {0}
      - name: Test
        run: |
          library(testthat)
          library(sommer)
          library(txtplot)
          library(simquantgen)
          devtools::load_all()
          devtools::document()
          devtools::test()
        shell: Rscript {0}
